# Generated by Django 5.0.6 on 2024-06-01 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cuil', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('domicilio', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('nroFactura', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('modoPago', models.CharField(max_length=200)),
                ('cuil', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(blank=True, upload_to='static/images')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='TipoProductos',
            fields=[
                ('idTipoProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo de producto',
                'verbose_name_plural': 'Tipos de Productos',
                'db_table': 'TipoProductos',
            },
        ),
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('nroFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hausmobel.facturas')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hausmobel.productos')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
                'db_table': 'Detalles',
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='idTipoProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hausmobel.tipoproductos'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('cuil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hausmobel.clientes')),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hausmobel.roles')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuarios',
            },
        ),
    ]
