# Generated by Django 4.2 on 2024-06-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hausmobel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
