# Generated by Django 4.2 on 2024-06-14 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hausmobel', '0002_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carritos',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('importe', models.FloatField()),
                ('Idusuario', models.IntegerField()),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hausmobel.productos')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'db_table': 'Carritos',
            },
        ),
    ]
